module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b6-1.png",
				spriteColorRect = { x = 0, y = 0, width = 235, height = 128 }, 
				textureRect = { x = 452, y = 164, width = 235, height = 128 }, 
				spriteSourceSize = { width = 235, height = 128 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-2.png",
				spriteColorRect = { x = 0, y = 0, width = 597, height = 163 }, 
				textureRect = { x = 305, y = 0, width = 597, height = 163 }, 
				spriteSourceSize = { width = 597, height = 163 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-3.png",
				spriteColorRect = { x = 0, y = 0, width = 145, height = 150 }, 
				textureRect = { x = 305, y = 164, width = 145, height = 150 }, 
				spriteSourceSize = { width = 145, height = 150 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-4.png",
				spriteColorRect = { x = 0, y = 0, width = 304, height = 364 }, 
				textureRect = { x = 0, y = 0, width = 304, height = 364 }, 
				spriteSourceSize = { width = 304, height = 364 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end