module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b5-1.png",
				spriteColorRect = { x = 0, y = 0, width = 247, height = 271 }, 
				textureRect = { x = 320, y = 613, width = 247, height = 271 }, 
				spriteSourceSize = { width = 247, height = 271 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-2.png",
				spriteColorRect = { x = 0, y = 0, width = 318, height = 395 }, 
				textureRect = { x = 0, y = 613, width = 318, height = 395 }, 
				spriteSourceSize = { width = 318, height = 395 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-3.png",
				spriteColorRect = { x = 0, y = 0, width = 465, height = 204 }, 
				textureRect = { x = 543, y = 0, width = 465, height = 204 }, 
				spriteSourceSize = { width = 465, height = 204 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-4.png",
				spriteColorRect = { x = 0, y = 0, width = 219, height = 225 }, 
				textureRect = { x = 543, y = 206, width = 219, height = 225 }, 
				spriteSourceSize = { width = 219, height = 225 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-5.png",
				spriteColorRect = { x = 0, y = 0, width = 541, height = 611 }, 
				textureRect = { x = 0, y = 0, width = 541, height = 611 }, 
				spriteSourceSize = { width = 541, height = 611 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end