module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b6-1.png",
				spriteColorRect = { x = 0, y = 0, width = 470, height = 257 }, 
				textureRect = { x = 0, y = 896, width = 470, height = 257 }, 
				spriteSourceSize = { width = 470, height = 257 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-2.png",
				spriteColorRect = { x = 0, y = 0, width = 597, height = 163 }, 
				textureRect = { x = 0, y = 731, width = 597, height = 163 }, 
				spriteSourceSize = { width = 597, height = 163 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-3.png",
				spriteColorRect = { x = 0, y = 0, width = 291, height = 301 }, 
				textureRect = { x = 0, y = 1155, width = 291, height = 301 }, 
				spriteSourceSize = { width = 291, height = 301 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b6-4.png",
				spriteColorRect = { x = 0, y = 0, width = 609, height = 729 }, 
				textureRect = { x = 0, y = 0, width = 609, height = 729 }, 
				spriteSourceSize = { width = 609, height = 729 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end