module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b7-1.png",
				spriteColorRect = { x = 0, y = 0, width = 142, height = 112 }, 
				textureRect = { x = 211, y = 286, width = 142, height = 112 }, 
				spriteSourceSize = { width = 142, height = 112 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-2.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 78 }, 
				textureRect = { x = 354, y = 286, width = 128, height = 78 }, 
				spriteSourceSize = { width = 128, height = 78 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-3.png",
				spriteColorRect = { x = 0, y = 0, width = 199, height = 131 }, 
				textureRect = { x = 211, y = 154, width = 199, height = 131 }, 
				spriteSourceSize = { width = 199, height = 131 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-4.png",
				spriteColorRect = { x = 0, y = 0, width = 102, height = 60 }, 
				textureRect = { x = 354, y = 366, width = 102, height = 60 }, 
				spriteSourceSize = { width = 102, height = 60 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-5.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 153 }, 
				textureRect = { x = 244, y = 0, width = 210, height = 153 }, 
				spriteSourceSize = { width = 210, height = 153 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-6.png",
				spriteColorRect = { x = 0, y = 0, width = 210, height = 319 }, 
				textureRect = { x = 0, y = 142, width = 210, height = 319 }, 
				spriteSourceSize = { width = 210, height = 319 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-7.png",
				spriteColorRect = { x = 0, y = 0, width = 91, height = 89 }, 
				textureRect = { x = 411, y = 154, width = 91, height = 89 }, 
				spriteSourceSize = { width = 91, height = 89 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b7-8.png",
				spriteColorRect = { x = 0, y = 0, width = 243, height = 141 }, 
				textureRect = { x = 0, y = 0, width = 243, height = 141 }, 
				spriteSourceSize = { width = 243, height = 141 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end