module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b8-1.png",
				spriteColorRect = { x = 0, y = 0, width = 752, height = 366 }, 
				textureRect = { x = 0, y = 0, width = 752, height = 366 }, 
				spriteSourceSize = { width = 752, height = 366 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-2.png",
				spriteColorRect = { x = 0, y = 0, width = 264, height = 160 }, 
				textureRect = { x = 0, y = 1200, width = 264, height = 160 }, 
				spriteSourceSize = { width = 264, height = 160 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-3.png",
				spriteColorRect = { x = 0, y = 0, width = 475, height = 258 }, 
				textureRect = { x = 0, y = 940, width = 475, height = 258 }, 
				spriteSourceSize = { width = 475, height = 258 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-4.png",
				spriteColorRect = { x = 0, y = 0, width = 706, height = 570 }, 
				textureRect = { x = 0, y = 368, width = 706, height = 570 }, 
				spriteSourceSize = { width = 706, height = 570 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end