module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b4-1.png",
				spriteColorRect = { x = 0, y = 0, width = 381, height = 478 }, 
				textureRect = { x = 0, y = 338, width = 381, height = 478 }, 
				spriteSourceSize = { width = 381, height = 478 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b4-2.png",
				spriteColorRect = { x = 0, y = 0, width = 668, height = 336 }, 
				textureRect = { x = 0, y = 0, width = 668, height = 336 }, 
				spriteSourceSize = { width = 668, height = 336 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b4-3.png",
				spriteColorRect = { x = 0, y = 0, width = 303, height = 176 }, 
				textureRect = { x = 670, y = 0, width = 303, height = 176 }, 
				spriteSourceSize = { width = 303, height = 176 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end