module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b8-1.png",
				spriteColorRect = { x = 0, y = 0, width = 376, height = 183 }, 
				textureRect = { x = 0, y = 0, width = 376, height = 183 }, 
				spriteSourceSize = { width = 376, height = 183 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-2.png",
				spriteColorRect = { x = 0, y = 0, width = 132, height = 80 }, 
				textureRect = { x = 0, y = 600, width = 132, height = 80 }, 
				spriteSourceSize = { width = 132, height = 80 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-3.png",
				spriteColorRect = { x = 0, y = 0, width = 237, height = 129 }, 
				textureRect = { x = 0, y = 470, width = 237, height = 129 }, 
				spriteSourceSize = { width = 237, height = 129 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b8-4.png",
				spriteColorRect = { x = 0, y = 0, width = 353, height = 285 }, 
				textureRect = { x = 0, y = 184, width = 353, height = 285 }, 
				spriteSourceSize = { width = 353, height = 285 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end