module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b3-1.png",
				spriteColorRect = { x = 0, y = 0, width = 567, height = 217 }, 
				textureRect = { x = 367, y = 211, width = 567, height = 217 }, 
				spriteSourceSize = { width = 567, height = 217 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b3-2.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 437 }, 
				textureRect = { x = 0, y = 211, width = 365, height = 437 }, 
				spriteSourceSize = { width = 365, height = 437 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b3-3.png",
				spriteColorRect = { x = 0, y = 0, width = 862, height = 209 }, 
				textureRect = { x = 0, y = 0, width = 862, height = 209 }, 
				spriteSourceSize = { width = 862, height = 209 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end