module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b2-1.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 98 }, 
				textureRect = { x = 0, y = 0, width = 84, height = 98 }, 
				spriteSourceSize = { width = 84, height = 98 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b2-2.png",
				spriteColorRect = { x = 0, y = 0, width = 154, height = 91 }, 
				textureRect = { x = 85, y = 0, width = 154, height = 91 }, 
				spriteSourceSize = { width = 154, height = 91 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end