module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b3-1.png",
				spriteColorRect = { x = 0, y = 0, width = 283, height = 108 }, 
				textureRect = { x = 183, y = 105, width = 283, height = 108 }, 
				spriteSourceSize = { width = 283, height = 108 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b3-2.png",
				spriteColorRect = { x = 0, y = 0, width = 182, height = 218 }, 
				textureRect = { x = 0, y = 105, width = 182, height = 218 }, 
				spriteSourceSize = { width = 182, height = 218 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b3-3.png",
				spriteColorRect = { x = 0, y = 0, width = 431, height = 104 }, 
				textureRect = { x = 0, y = 0, width = 431, height = 104 }, 
				spriteSourceSize = { width = 431, height = 104 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end