module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
--
-- Usage example:
--			local zwoptexData = require "ThisFile.lua"
-- 			local data = zwoptexData.getSpriteSheetData()
--			local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
--
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

function getSpriteSheetData()

	local sheet = {
		frames = {
		
			{
				name = "b5-1.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 135 }, 
				textureRect = { x = 160, y = 306, width = 123, height = 135 }, 
				spriteSourceSize = { width = 123, height = 135 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-2.png",
				spriteColorRect = { x = 0, y = 0, width = 159, height = 197 }, 
				textureRect = { x = 0, y = 306, width = 159, height = 197 }, 
				spriteSourceSize = { width = 159, height = 197 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-3.png",
				spriteColorRect = { x = 0, y = 0, width = 232, height = 102 }, 
				textureRect = { x = 271, y = 0, width = 232, height = 102 }, 
				spriteSourceSize = { width = 232, height = 102 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-4.png",
				spriteColorRect = { x = 0, y = 0, width = 109, height = 112 }, 
				textureRect = { x = 271, y = 103, width = 109, height = 112 }, 
				spriteSourceSize = { width = 109, height = 112 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
			{
				name = "b5-5.png",
				spriteColorRect = { x = 0, y = 0, width = 270, height = 305 }, 
				textureRect = { x = 0, y = 0, width = 270, height = 305 }, 
				spriteSourceSize = { width = 270, height = 305 }, 
				spriteTrimmed = true,
				textureRotated = false
			},
		
		}
	}

	return sheet
end